env: dev  # "dev", "prod", "local"

connection_string: "host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} sslmode=disable"

grpc:
  port: 50055
  address: ":50055"
  timeout: 10s

secret: ${SECRET}
