env: local

connection_string: "host=localhost port=5432 user=tomatocoder password=postgres dbname=repeatro sslmode=disable"

grpc:
  port: 50055
  address: ":50055"
  timeout: 10s

secret: ${SECRET}
