env: "local"  #dev, prod, local
conecction_max_lifetime: 60s
connection_string: "host=localhost port=5432 user=tomatocoder password=postgres dbname=repeatro sslmode=disable"
driver_name: "postgres"
grpc:  
  address: ":44044"
  timeout: 10h