env: dev  # "dev", "prod", "local"

connection_string: "host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} sslmode=disable"

grpc:
  port: 44044
  address: ":44044"
  timeout: 10s

token_ttl: 15m

secret: ${SECRET}
