env: dev      # "dev", "prod", "local"

database:
  driver_name: postgres
  # можно подставлять из env, если настроить обработку ${…}
  connection_string: >-
    host=${DB_HOST} port=${DB_PORT}
    user=${DB_USER} password=${DB_PASS}
    dbname=${DB_NAME} sslmode=disable
  max_idle_connections: 5
  max_open_connections: 20
  max_lifetime: 60s

grpc:
  address: ":50051"
  timeout: 10s

http:
  address: ":44044"
  read_timeout: 5s
  write_timeout: 5s

keys:
  private_key_file: "config/private.pem"
  public_key_file:  "config/public.pem"

auth:
  access_token_ttl: 15m
  refresh_token_ttl: 24h

logger:
  level: info       # debug / info / warn / error
  format: text      # text / json