env: "local"
connection_string: "host=localhost port=5432 user=tomatocoder password=postgres dbname=repeatro sslmode=disable"
http_server:
  address: "0.0.0.0:8081"
  timeout: 4s
  idle_timeout: 30s
clients:
  sso:
    address: "localhost:44044"
secret: "some very secret secret"
grpc:
  port: 50051
  timeout: 10h