env: "local"
connection_string: "host=localhost port=5432 user=tomatocoder password=postgres dbname=repeatro sslmode=disable"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
secret: "some very secret secret"