services:
  postgres-card:
    image: postgres:15
    container_name: postgres-card
    restart: always
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_card_data:/var/lib/postgresql/data

  card:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: card-service
    env_file:
      - ./.env
    ports:
      - "8101:8081"
    depends_on:
      - postgres-card
    volumes:
      - ${CONFIG_PATH}:/app/config/config.yaml

volumes:
  postgres_card_data: