version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: repeatro
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  sso:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: sso-service
    depends_on:
      - postgres
    ports:
      - "44044:44044"
    environment:  
      CONFIG_PATH: ./config/config.yaml     # Or use external config strategy
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./config:/app/config
    

volumes:
  postgres_data: