version: '3.9'

services:
  postgres-sso:
    image: postgres:15
    container_name: postgres-sso
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_sso_data:/var/lib/postgresql/data

  sso:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sso-service
    env_file:
      - .env
    ports:
      - "8001:44044"
    depends_on:
      - postgres-sso
    volumes:
      - ./config:/app/config
      - .env:/app/.env  # 👈 нужно для godotenv

volumes:
  postgres_sso_data: