services:
  postgres-repeatro:
    image: postgres:15
    container_name: postgres-repeatro
    restart: always
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_repeatro_data:/var/lib/postgresql/data

  repeatro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repeatro-service
    env_file:
      - ./.env
    ports:
      - "8101:8081"
    depends_on:
      - postgres-repeatro
    volumes:
      - ${CONFIG_PATH}:/app/config/config.yaml

volumes:
  postgres_repeatro_data: