env: local

connection_string: "host=localhost port=5432 user=tomatocoder password=postgres dbname=repeatro sslmode=disable"

grpc:
  port: 50054
  address: ":50054"
  timeout: 10h

secret: ${SECRET}
