env: dev # "dev", "prod", "local"

connection_string: "host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} sslmode=disable"

clients:
  card:
    address: "card-service:${CARD_CONTAINER_PORT}"
    timeout: 5s
    retries_count: 3
  deck:
    address: "deck-service:${DECK_CONTAINER_PORT}"
    timeout: 5s
    retries_count: 3
  sso:
    address: "sso-service:${SSO_CONTAINER_PORT}"
    timeout: 5s
    retries_count: 3
  stat:
    address: "stat-service:${STAT_CONTAINER_PORT}"
    timeout: 5s
    retries_count: 3

grpc:
  port: 50054
  address: ":50054"
  timeout: 10s

http_server:
  address: "0.0.0.0:8400"
  port: 8400
  timeout: 4s
  idle_timeout: 30s

secret: ${SECRET}
