env: "local"
connection_string: "host=localhost port=5432 user=tomatocoder password=postgres dbname=repeatro sslmode=disable"
http_server:
  address: "0.0.0.0:8080"
  portt: 8081
  timeout: 4s
  idle_timeout: 30s
clients:
  sso:
    address: "localhost:44044"
  card:
    address: "localhost:50051"
  deck:
    address: "localhost:50054"
  stat:
    address: "localhost:50055"
secret: "some very secret secret"